### ISSUE TITLE
Jenkins Tray Project

### ISSUE THREAD

**Issue by zionyx** [aseigneurin/hudson-tray-tracker#4]
Hello Alex,

Thank you for your project. It helped us a lot. Now that the development of Hudson tray tracker has become stagnant, I wish to request to take over the project under a new name, Jenkins Tray Project to release it as Jenkins Tray.

https://github.com/zionyx/jenkins-tray

This is a formal request. Please let me know if there are any concern in terms of legality. Thank you.

Best Regards,
Lee

**Comment by aseigneurin** [comment]
Hi Lee,

No problem. Please feel free to fork and rename the project.
Of course, I'll be happy if you can leave a note somewhere in the "about"
section of the app mentioning the original project :)

Alexis

2015-01-22 14:42 GMT+01:00 Tuk <notifications@github.com>:

**Comment by zionyx** [comment]
Hi Alexis,

Thank you. The app will always present the origin of the project. :)

Lee
